sudo: required
services:
  - docker

#
# series of commands to run before running tests
#

# -t  for tagging image you can name it anything

before_install:
  - docker build -t singhadev01/docker-react -f Dockerfile.dev .


#
# series of command to run as part of test suite
# if u get status code !=0  then travis assum test failed

# override defauly run command with nom run test
script:
  - docker run singhadev01/docker-react npm run test -- --coverage


#
# travis ci comes up with option to deploy to predefined providers
# travis ci will zip our code from master branch and push to s3 bucket
# sepecify app name value as bucket_path

# use awas api key to grant travis-ci access  to aws

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-916434611368"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"

