#Use an existing docaker image as base
FROM node:alpine

#Workdir - for copying file to container
WORKDIR '/app'

#Download and install a dependency
COPY package.json .
RUN npm install

COPY . .

# Tell image what to do when it starts as container
CMD ["npm", "run", "start"]
